# Generated by Django 6.0.5 on 2026-05-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_missing_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('Ingénierie Informatique & Réseaux', 'Ingénierie Informatique & Réseaux'), ('Ingénierie Automatisme et Informatique Industrielle', 'Ingénierie Automatisme et Informatique Industrielle'), ('Génie Industriel', 'Génie Industriel')], max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_year',
            field=models.CharField(blank=True, choices=[('1ère année', '1ère année'), ('2ème année', '2ème année'), ('3ème année', '3ème année'), ('4ème année', '4ème année'), ('5ème année', '5ème année')], max_length=80),
        ),
        migrations.AlterField(
            model_name='tutorapplication',
            name='department',
            field=models.CharField(choices=[('Ingénierie Informatique & Réseaux', 'Ingénierie Informatique & Réseaux'), ('Ingénierie Automatisme et Informatique Industrielle', 'Ingénierie Automatisme et Informatique Industrielle'), ('Génie Industriel', 'Génie Industriel')], max_length=120),
        ),
        migrations.AlterField(
            model_name='tutorapplication',
            name='level',
            field=models.CharField(choices=[('1ère année', '1ère année'), ('2ème année', '2ème année'), ('3ème année', '3ème année'), ('4ème année', '4ème année'), ('5ème année', '5ème année')], max_length=80),
        ),
    ]
