# Generated by Django 6.0.5 on 2026-05-16 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_department_alter_profile_study_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('request_type', models.CharField(choices=[('account', 'Creation de compte'), ('tutor', 'Activation mode tuteur'), ('login', 'Probleme de connexion'), ('other', 'Autre demande')], default='account', max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='contact_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to='accounts.contactadminmessage'),
        ),
    ]
