# Generated by Django 6.0.5 on 2026-05-16 22:14

from django.db import migrations, models


def force_in_person(apps, schema_editor):
    TutorApplication = apps.get_model('accounts', 'TutorApplication')
    TutorApplication.objects.exclude(session_mode='in_person').update(session_mode='in_person')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_contactadminmessage_and_more'),
    ]

    operations = [
        migrations.RunPython(force_in_person, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tutorapplication',
            name='session_mode',
            field=models.CharField(choices=[('in_person', 'Présentiel')], default='in_person', max_length=30),
        ),
    ]
