# Generated by Django 6.0.5 on 2026-05-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_tutorapplication_session_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactadminmessage',
            name='request_type',
            field=models.CharField(choices=[('account', 'Creation de compte'), ('tutor', 'Activation mode tuteur'), ('login', 'Probleme de connexion'), ('other', 'Autre demande'), ('account_info', 'Informations de compte incorrectes')], default='account', max_length=30),
        ),
    ]
