# Generated by Django 6.0.5 on 2026-05-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('department', 'study_year', 'name')},
        ),
        migrations.AddField(
            model_name='subject',
            name='study_year',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name', 'department', 'study_year'), name='unique_subject_by_department_year'),
        ),
    ]
