# Generated by Django 6.0.5 on 2026-05-16 22:14

from django.db import migrations, models


def force_in_person(apps, schema_editor):
    Availability = apps.get_model('availability', 'Availability')
    Availability.objects.exclude(mode='in_person').update(mode='in_person')


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(force_in_person, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='availability',
            name='mode',
            field=models.CharField(choices=[('in_person', 'Présentiel')], default='in_person', max_length=30),
        ),
    ]
