# Generated by Django 6.0.5 on 2026-05-16 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_alter_availability_mode'),
        ('tutoring_sessions', '0002_room_tutoringsession_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availabilities', to='tutoring_sessions.room'),
        ),
    ]
