# Generated by Django 6.0.5 on 2026-05-16 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_availability_room'),
        ('subjects', '0002_alter_subject_options_subject_study_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availabilities', to='subjects.subject'),
        ),
    ]
