# Generated by Django 6.0.5 on 2026-05-15 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messages_app', '0001_initial'),
        ('tutoring_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='tutoring_sessions.tutoringsession'),
        ),
    ]
